### ISSUE TITLE
Autocomplete with Rx example doesn't seem to be working

### ISSUE THREAD

**Issue by JamieVaughn** [ChetHarrison/A-Gentle-Introduction-to-Functional-JavaScript#1]
I remember it working a few months ago when I first tried it after watching your interview with Derrick Bailey (very interesting, btw). Perhaps the cdn library import needs to be updated?

**Comment by ChetHarrison** [comment]
Hey Jamie

I’m out until Monday. You can contact me then. In the meantime here is a link to a 3 part YouTube series I did with Derick Bailey. The 3rd part covers Rx in depth. Jest bear in mind it is probably over 5 years old!

https://youtu.be/myISHtMMeyU

Chet Harrison
949 933 1307
